require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/FilePath:
  Exclude:
    - "config/environments/development.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "app/controllers/users/**/*"
