databases:
  - name: アプリ名_db
    databaseName: アプリ名_production
    region: singapore
    plan: free

services:
  - type: web
    name: アプリ名_web
    env: ruby
    region: singapore
    plan: free
    branch: main
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: アプリ名_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
